name: Android Firebase App Distribution Workflow

on:
  push:
    branches:
      - development
      - master
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'


      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.6"
          bundler-cache: true
          working-directory: android


      - name: Build and distribute app
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane android firebase_distribution
        working-directory: android